version: '3'
services:
  fastbot-ros2-real:
    image: akitsuyoshi/akitsuyoshi-cp22:fastbot-ros2-real
    # build:
    #   context: ../..
    #   dockerfile: fastbot_ros2_docker/real/Dockerfile.real
    container_name: fastbot-ros2-real
    privileged: true
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds_husarnet.xml
    volumes:
      - /var/lib/theconstruct.rrl/:/var/lib/theconstruct.rrl/
      - /dev:/dev
    entrypoint: /ros_entrypoint.sh
    command: bash -c "source /opt/ros/humble/setup.bash && source /root/ros2_ws/install/setup.bash && ros2 launch fastbot_bringup bringup.launch.xml"
    restart: always
  
  fastbot-ros2-real-slam:
    image: akitsuyoshi/akitsuyoshi-cp22:fastbot-ros2-slam-real
    # build:
    #   context: ../..
    #   dockerfile: fastbot_ros2_docker/real/Dockerfile.slam
    container_name: fastbot-ros2-real-slam
    network_mode: host
    depends_on:
      - fastbot-ros2-real
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=1
      - CYCLONEDDS_URI=/var/lib/theconstruct.rrl/cyclonedds_husarnet.xml
    volumes:
      - /var/lib/theconstruct.rrl/:/var/lib/theconstruct.rrl/
    entrypoint: /ros_entrypoint.sh
    command: bash -c "source /opt/ros/humble/setup.bash && source /ros2_ws/install/setup.bash && ros2 launch fastbot_slam cartographer.launch.py"
    restart: always